### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by zikai-11** [rain152/PAT#1]
你好，当我运行代码时遇到如下错误，这个我不知道怎么解决，能帮助我一下吗？
Traceback (most recent call last):
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../main.py", line 130, in <module>
    app.run(main)
  File "/root/miniconda3/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../main.py", line 105, in main
    attack.run(
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../../llm_attacks/base/attack_manager.py", line 1633, in run
    attack.run(
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../../llm_attacks/base/attack_manager.py", line 1012, in run
    def_control, def_loss = self.defense_step(
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../../llm_attacks/gcg/gcg_attack.py", line 309, in defense_step
    self.prompts[k].update_benign_idx()
  File "/root/autodl-tmp/PAT/experiments/launch_scripts/../../llm_attacks/base/attack_manager.py", line 674, in update_benign_idx
    self.benign_idx = np.random.permutation(len(self._benign_prompts))
AttributeError: 'GCGPromptManager' object has no attribute '_benign_prompts'. Did you mean: 'get_benign_prompt'?

**Comment by rain152** [comment]
Could you provide your complete running prompt in the bash script?

**Comment by zikai-11** [comment]
![4L`TRNKZYJWG4Q{)M%BL5M7](https://github.com/user-attachments/assets/cb3e8158-28d5-4031-a4dd-89be31d31aa4)

**Comment by rain152** [comment]
Do you run the following command?  
`bash run_gcg_multiple.sh vicuna 15 0.2 0`

**Comment by zikai-11** [comment]
yes My parameters are as follows.
![G1G%XM`75~O)JYD)$3B 7LY](https://github.com/user-attachments/assets/05b3b91c-a071-4adf-b6fe-c6bfdf9f4e0c)

**Comment by rain152** [comment]
The initialization of _benign_prompts can be found at _attack_manager.py line 606_ . Could you please print some intermediate variables here to help debug?

**Comment by zikai-11** [comment]
The parameter benign_file is not passed into attack = attack_lib.IndividualPromptAttack in main.py，Is the reason that the condition at line 605 in attack_manager.py is not being met？

**Comment by zikai-11** [comment]
作者您好，我已成功运行代码，非常感谢您的回复，希望您天天开心。

**Comment by rain152** [comment]
Thank you for your interest in our work🙂, if you have any other questions or find any bugs, please feel free to communicate.
